# This is a basic workflow to help you get started with Actions

name: Update Waka Time

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  schedule:
    # Runs at 12am CST
    - cron: "0 22 * * *"

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      
      - name: Waka - Readme
        # You may pin to the exact commit or the version.
        # uses: athul/waka-readme@1f2d0f1334ec066ef92b9eaf14242cd062bcd254
        uses: athul/waka-readme@v0.1.5
        with:
          # GitHub access token with Repo scope
          # GH_TOKEN: # default is ${{ github.token }}
          # Your Wakatime API Key
          WAKATIME_API_KEY: ${{ secrets.WAKATIME_API_KEY }}
          # Your GitHub repository
          # REPOSITORY: # optional, default is ${{ github.repository }}
          # Displays the week number and days in Readme as title
          SHOW_TITLE: true # optional
          # Add a commit message of your choice
          # COMMIT_MESSAGE: # optional, default is Updated the Graph with new Metrics
          # Add the progress blocks of your choice
          BLOCKS: ⣀⣄⣤⣦⣶⣷⣿ # optional, default is ░▒▓█
